################
### Language ###
################
language: java

###########
### JDK ###
###########
jdk:
  - oraclejdk11

#####################
### Notifications ###
#####################
notifications:
  email: false

####################
### Build script ###
####################
script:
  - mvn clean compile package cobertura:cobertura

##################
### POST Build ###
##################
after_success:
- bash <(curl -s https://codecov.io/bash)
