################
### Language ###
################
language: java

###########
### JDK ###
###########
jdk:
  - oraclejdk11

#####################
### Notifications ###
#####################
notifications:
  email: false

####################
### Build script ###
####################
script:
  - mvn clean compile package

##################
### Deployment ###
##################
deploy:
  provider: script
  script: mvn deploy --settings deploy/maven-settings.xml
  on:
    branch: master
    tags: true

env:
  global:
  - secure: JCpnsTYBk7W/g8Wre4vqYZqu2TgKOPBu/oSjsAKu8GYnRczWoQlFzlbXAMQe1GdtObuVzWqdzKGNtdXQj9o+5zYJBZhxetzqJXWSnU3uM4LqdUv7l0bKm5HeqKGjcY8Ns6YecZ9/GjvM+K3LXnm0zjWwzToABrbzLcT3ow1o65lRGAECuwEq9pbTILc8f0ISSwRStcimtMJz1QLDVFFhiGQtYbIb8/YQT3nosbLm0DhmF/tCJhQ8lZw4buK+xHTWJHM+k/1rx/+U3SXK/7xzqXNBy+QxK6l+ncr4S+vpSW96C/WokDepCo1XTUaf5N+rESj4yCH/YH/OtZH6oDRm/Rbp1sesKlPkt3B2TD2++y8zr8rk2L16z0omMpJ/vXJTh2yFLUgi/czb4UOO2N/8sZ7z7eweXaHC7jL2RuDoomkJ4t2w3W5//829h6kbfzkbwRZmi/J26racz2yVlC0l8qgISwjc+8yP8yD+TBd4pyNbskd7xpnsWbvDsmI+1dZ3v2jYFgyprfZ2MEa4GLheLfduYTUYwW1koEM9oBWBHNFhZs5tSuurAE13dvPpUakXjiLO7hRvtsCX/o/04LNV6UhXYUvHBKaXHgR52y0H7Qfc77kxYDHIifhn+kjUnvLb6GAjDhQnJ2GdOJ8+YPyiV24M5EisbHy1Z3qV2q6FpQo=
  - secure: V/qNvlUa5oSvLVYRZfwaeC1YVkwYPMkNMZeJc9iBKmJm7XGZlLl3vdEk2LkqtdJBPMOH1SjheFoR3BbKRePPZl06+uPHjXKpEUTjmeOCED4nohInmWm6WG4hGatI7lhtMX24ihvZgu/5ioNbupsAkigPGh5Miu/hhmwnYwnMf3aLnGah9y+H6rapDRaZqGD1IKur/S1AUF4OgX2bPZNzbvqZvaTXcobAH/pIoZBmQT1xou4VtqTqkNWp4pYbgMf1hkpF23xo3h6+7VGQnKR1ybpcD1i6Bs7+DOA8kvYNY9yn49vSu+9hkSvVxqh8hk9bnC/GO/PRaXEyTLuOhUwiBTKmzpyOtQDAsQ1yJ1vW5yzHyUaY8N6d4gB7qzSO4u190Z75ywNQuKVFjpv+MvGx07aDI8jzDnoD8uuq8BQKiwNOnk4cPDo+KaIxfUWnijuzJEFoPpehWgjs7cBQpjMzb02DnTdATTOxInJ3SiQ0qFYv2aCJU3BhDgK95sLszy1hwLUMu1YAHkeWC1+QBAfvoEpMpHJiDEn7j4A8XiyuZ1MbvMUbGHeJL8g7WLa7aR4XB2zfbjVrj0izcllpeKApYqRR/mdNuj9dNAQ5mGYIhcxfYE2LJeHMiAgSFRWOLi9h6vkHB1uuVk5VOqtng6f4UKvlU0IeQMDPMNyoofg00cs=
